config/routes.rb
Openfoodnetwork::Application.routes.draw do
  root :to => 'home#index'

  # Redirects from old URLs avoid server errors and helps search engines
  get "/enterprises", to: redirect("/")
  get "/products", to: redirect("/")
  get "/products/:id", to: redirect("/")
  get "/t/products/:id", to: redirect("/")
  get "/about_us", to: redirect(ContentConfig.footer_about_url)

  get "/#/login", to: "home#index", as: :spree_login
  get "/login", to: redirect("/#/login")

  get "/discourse/login", to: "discourse_sso#login"
  get "/discourse/sso", to: "discourse_sso#sso"

  get "/map", to: "map#index", as: :map
  get "/sell", to: "home#sell", as: :sell

  get "/register", to: "registration#index", as: :registration
  get "/register/auth", to: "registration#authenticate", as: :registration_auth

  # Redirects to global website
  get "/connect", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/connect/")
  get "/learn", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/learn/")

  resource :shop, controller: "shop" do
    get :products
    post :order_cycle
    get :order_cycle
    get :changeable_orders_alert
  end

  resources :producers, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :shops, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :line_items, only: [:destroy] do
    get :bought, on: :collection
  end

  resources :groups, only: [:index, :show] do
    collection do
      get :signup
    end
  end

  get '/checkout', :to => 'checkout#edit' , :as => :checkout
  put '/checkout', :to => 'checkout#update' , :as => :update_checkout
  get '/checkout/paypal_payment/:order_id', to: 'checkout#paypal_payment', as: :paypal_payment

  get 'embedded_shopfront/shopfront_session', to: 'application#shopfront_session'
  post 'embedded_shopfront/enable', to: 'application#enable_embedded_styles'
  post 'embedded_shopfront/disable', to: 'application#disable_embedded_styles'

  resources :enterprises do
    collection do
      post :search
      get :check_permalink
    end

    member do
      get :shop
      get :relatives
    end
  end
  get '/:id/shop', to: 'enterprises#shop', as: 'enterprise_shop'
  get "/enterprises/:permalink", to: redirect("/") # Legacy enterprise URL

  devise_for :enterprise, controllers: { confirmations: 'enterprise_confirmations' }

  namespace :admin do
    resources :order_cycles do
      post :bulk_update, on: :collection, as: :bulk_update

      member do
        get :clone
        post :notify_producers
      end
    end

    resources :enterprises do
      collection do
        get :for_order_cycle
        get :for_line_items
        post :bulk_update, as: :bulk_update
      end

      member do
        get :welcome
        put :register
      end

      resources :producer_properties do
        post :update_positions, on: :collection
      end

      resources :tag_rules, only: [:destroy]
    end

    resources :enterprise_relationships
    resources :enterprise_roles

    resources :enterprise_fees do
      collection do
        get :for_order_cycle
        post :bulk_update, :as => :bulk_update
      end
    end

    resources :enterprise_groups do
      get :move_up
      get :move_down
    end

    get '/inventory', to: 'variant_overrides#index'

    get '/product_import', to: 'product_import#index'
    post '/product_import', to: 'product_import#import'
    post '/product_import/save', to: 'product_import#save', as: 'product_import_save'

    resources :variant_overrides do
      post :bulk_update, on: :collection
      post :bulk_reset, on: :collection
    end

    resources :inventory_items, only: [:create, :update]

    resources :customers, only: [:index, :create, :update, :destroy]

    resources :tag_rules, only: [], format: :json do
      get :map_by_tag, on: :collection
    end

    resource :content

    resource :accounts_and_billing_settings, only: [:edit, :update] do
      collection do
        get :show_methods
        get :start_job
      end
    end

    resource :business_model_configuration, only: [:edit, :update], controller: 'business_model_configuration'

    resource :cache_settings

    resource :account, only: [:show], controller: 'account'

    resources :column_preferences, only: [], format: :json do
      put :bulk_update, on: :collection
    end

    resource :invoice_settings, only: [:edit, :update]
  end

  namespace :api do
    resources :enterprises do
      post :update_image, on: :member
      get :managed, on: :collection
      get :accessible, on: :collection
    end
    resources :order_cycles do
      get :managed, on: :collection
      get :accessible, on: :collection
    end

    resource :status do
      get :job_queue
    end
  end

  namespace :open_food_network do
    resources :cart do
      post :add_variant
    end
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  # Mount Spree's routes
  mount Spree::Core::Engine, :at => '/'

end


# Overriding Devise routes to use our own controller
Spree::Core::Engine.routes.draw do
  devise_for :spree_user,
             :class_name => 'Spree::User',
             :controllers => { :sessions => 'spree/user_sessions',
                               :registrations => 'user_registrations',
                               :passwords => 'user_passwords' },
             :skip => [:unlocks, :omniauth_callbacks],
             :path_names => { :sign_out => 'logout' },
             :path_prefix => :user
end



Spree::Core::Engine.routes.prepend do
  match '/admin/reports/orders_and_distributors' => 'admin/reports#orders_and_distributors', :as => "orders_and_distributors_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/order_cycle_management' => 'admin/reports#order_cycle_management', :as => "order_cycle_management_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/packing' => 'admin/reports#packing', :as => "packing_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/group_buys' => 'admin/reports#group_buys', :as => "group_buys_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/bulk_coop' => 'admin/reports#bulk_coop', :as => "bulk_coop_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/payments' => 'admin/reports#payments', :as => "payments_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/orders_and_fulfillment' => 'admin/reports#orders_and_fulfillment', :as => "orders_and_fulfillment_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/users_and_enterprises' => 'admin/reports#users_and_enterprises', :as => "users_and_enterprises_admin_reports",  :via => [:get, :post]
  match '/admin/reports/sales_tax' => 'admin/reports#sales_tax', :as => "sales_tax_admin_reports",  :via  => [:get, :post]
  match '/admin/products/bulk_edit' => 'admin/products#bulk_edit', :as => "bulk_edit_admin_products"
  match '/admin/orders/bulk_management' => 'admin/orders#bulk_management', :as => "admin_bulk_order_management"
  match '/admin/reports/products_and_inventory' => 'admin/reports#products_and_inventory', :as => "products_and_inventory_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/customers' => 'admin/reports#customers', :as => "customers_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/xero_invoices' => 'admin/reports#xero_invoices', :as => "xero_invoices_admin_reports",  :via  => [:get, :post]
  match '/admin', :to => 'admin/overview#index', :as => :admin
  match '/admin/payment_methods/show_provider_preferences' => 'admin/payment_methods#show_provider_preferences', :via => :get


  namespace :api, :defaults => { :format => 'json' } do
    resources :users do
      get :authorise_api, on: :collection
    end

    resources :products do
      collection do
        get :managed
        get :bulk_products
        get :overridable
      end
      delete :soft_delete

      resources :variants do
        delete :soft_delete
      end
    end

    resources :orders do
      get :managed, on: :collection
    end
  end

  namespace :admin do
    get '/search/known_users' => "search#known_users", :as => :search_known_users
    get '/search/customers' => 'search#customers', :as => :search_customers

    resources :products do
      get :product_distributions, on: :member

      post :bulk_update, :on => :collection, :as => :bulk_update
    end

    resources :orders do
      get :invoice, on: :member
      get :print, on: :member
      get :print_ticket, on: :member
      get :managed, on: :collection
    end

    resources :line_items, only: [:index], format: :json
  end

  resources :orders do
    get :clear, :on => :collection
    get :order_cycle_expired, :on => :collection
    put :cancel, on: :member
  end

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
  # Inherit CanCan permissions for the current order
  def model_class
    load_order unless @order
    @order
  end
end

app/helpers/spree/orders_helper.rb
module Spree
  module OrdersHelper
    def cart_is_empty
      order = current_order(false)
      order.nil? || order.line_items.empty?
    end

    def alternative_available_distributors(order)
      DistributionChangeValidator.new(order).available_distributors(Enterprise.all) - [order.distributor]
    end

    def last_completed_order
      spree_current_user.orders.complete.last
    end

    def cart_count
      current_order.andand.line_items.andand.count || 0
    end

    def changeable_orders
      # Only returns open order for the current user + shop + oc combo
      return @changeable_orders unless @changeable_orders.nil?
      return @changeable_orders = [] unless spree_current_user && current_distributor && current_order_cycle
      return @changeable_orders = [] unless current_distributor.allow_order_changes?
      @changeable_orders = Spree::Order.complete.where(
        state: 'complete',
        user_id: spree_current_user.id,
        distributor_id: current_distributor.id,
        order_cycle_id: current_order_cycle.id)
    end

    def changeable_orders_link_path
      changeable_orders.one? ? spree.order_path(changeable_orders.first) : spree.account_path
    end

    def shop_changeable_orders_alert_html
      return "" unless changeable_orders.any?
      t(:shop_changeable_orders_alert_html,
        count: changeable_orders.count,
        path: changeable_orders_link_path,
        order: changeable_orders.first.number,
        shop: current_distributor.name,
        oc_close: l(current_order_cycle.orders_close_at, format: "%A, %b %d, %Y @ %H:%M"))
    end
  end
end

app/views/spree/admin/orders/_capture.html.haml
- # Get the payment in 'checkout' state if any, and show capture button
- if order.payments.present?
  - payment = order.payments.select{|p| p if p.state == 'checkout'}.first
  - if !payment.nil?
    - payment.actions.grep(/^capture$/).each do |action|
      - # copied from backend/app/views/spree/admin/payments/_list.html.erb
      = link_to_with_icon "icon-#{action}", t('admin.orders.index.capture'), fire_admin_order_payment_path(order, payment, :e => action), :method => :put, :no_text => true, :data => {:action => action}

app/views/spree/admin/orders/_invoice_table.html.haml
%table.order-summary{:width => "100%"}
  %thead
    %tr
      %th{:align => "left"}
        %h4= t(:invoice_column_item)
      %th{:align => "right", :width => "15%"}
        %h4= t(:invoice_column_qty)
      %th{:align => "right", :width => "15%"}
        %h4= @order.total_tax > 0 ? t(:invoice_column_tax) : ""
      %th{:align => "right", :width => "15%"}
        %h4= t(:invoice_column_price)
  %tbody
    - @order.line_items.sort_by{ |li| li.product.name }.each do |item|
      %tr
        %td
          = render 'spree/shared/line_item_name', line_item: item
        %td{:align => "right"}
          = item.quantity
        %td{:align => "right"}
          = item.included_tax > 0 ? item.display_included_tax : ""
        %td{:align => "right"}
          = item.display_amount_with_adjustments
    - checkout_adjustments_for(@order, exclude: [:line_item]).reject{ |a| a.amount == 0 }.reverse_each do |adjustment|
      %tr
        %td
          %strong= "#{raw(adjustment.label)}"
        %td{:align => "right"}
          1
        %td{:align => "right"}
          = adjustment.included_tax > 0 ? adjustment.display_included_tax : ""
        %td{:align => "right"}
          = adjustment.display_amount
  %tfoot
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong= t(:invoice_tax_total)
      %td{:align => "right", :colspan => "2"}
        %strong= display_checkout_tax_total(@order)
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong= t(:total_excl_tax)
      %td{:align => "right", :colspan => "2"}
        %strong= display_checkout_total_less_tax(@order)
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong= t(:total_incl_tax)
      %td{:align => "right", :colspan => "2"}
        %strong= @order.display_total
%p
  &nbsp;

app/views/spree/admin/orders/_invoice_table2.html.haml
%table.order-summary{:width => "100%"}
  %thead
    %tr
      %th{:align => "left"}
        %h5= t(:invoice_column_item)
      %th{:align => "right", :width => "15%"}
        %h5= t(:invoice_column_qty)
      %th{:align => "right", :width => "15%"}
        %h5= @order.has_taxes_included ? t(:invoice_column_unit_price_with_taxes) : t(:invoice_column_unit_price_without_taxes)
      %th{:align => "right", :width => "15%"}
        %h5= @order.has_taxes_included ? t(:invoice_column_price_with_taxes) : t(:invoice_column_price_without_taxes)
      - if @order.total_tax > 0
        %th{:align => "right", :width => "15%"}
          %h5= t(:invoice_column_tax_rate)
  %tbody
    - @order.line_items.sort_by{ |li| li.product.name }.each do |item|
      %tr
        %td
          = render 'spree/shared/line_item_name', line_item: item
        %td{:align => "right"}
          = item.quantity
        %td{:align => "right"}
          = item.single_display_amount_with_adjustments
        %td{:align => "right"}
          = item.display_amount_with_adjustments
        - if @order.total_tax > 0
          %td{:align => "right"}
            = display_line_item_tax_rates(item)
    - checkout_adjustments_for(@order, exclude: [:line_item]).reject{ |a| a.amount == 0 }.reverse_each do |adjustment|
      %tr
        %td
          %strong= "#{raw(adjustment.label)}"
        %td{:align => "right"}
        %td{:align => "right"}
        %td{:align => "right"}
          = adjustment.display_amount
        - if @order.total_tax > 0
          %td{:align => "right"}
            = display_adjustment_tax_rates(adjustment)
  %tfoot
    %tr
      %td{:align => "right", :colspan => "3"}
        %strong= @order.has_taxes_included ? t(:total_incl_tax) : t(:total_excl_tax)
      %td{:align => "right", :colspan => "2"}
        %strong= @order.has_taxes_included ? @order.display_total : display_checkout_total_less_tax(@order)
    - display_checkout_taxes_hash(@order).each do |tax_rate, tax_value|
      %tr
        %td{:align => "right", :colspan => "3"}
          = t(:tax_total, rate: tax_rate)
        %td{:align => "right", :colspan => "2"}
          = tax_value
    %tr
      %td{:align => "right", :colspan => "3"}
        = @order.has_taxes_included ? t(:total_excl_tax) : t(:total_incl_tax)
      %td{:align => "right", :colspan => "2"}
        = @order.has_taxes_included ? display_checkout_total_less_tax(@order) : @order.display_total
%p
  &nbsp;

app/views/spree/admin/orders/edit.html.haml
= csrf_meta_tags

- content_for :page_actions do
  %li= event_links
  %li= button_link_to t(:resend), resend_admin_order_url(@order), method: :post, icon: 'icon-email'
  %li= button_link_to t(:back_to_orders_list), admin_orders_path, icon: 'icon-arrow-left'

= admin_inject_shops 'admin.orders'
= admin_inject_order_cycles

= render 'spree/admin/shared/order_tabs', current: 'Order Details'

%div{"data-hook" => "admin_order_edit_header"}
  = render 'spree/shared/error_messages', target: @order

%div{"ng-app" => "admin.orders", "ng-controller" => "ordersCtrl", "ofn-distributor-id" => @order.distributor_id, "ofn-order-cycle-id" => @order.order_cycle_id}
  = render 'add_product'

  %div{"data-hook" => "admin_order_edit_form"}
    #order-form-wrapper
      = render 'form', order: @order

- content_for :head do
  = javascript_tag 'var expand_variants = true;'

app/views/spree/admin/orders/invoice.html.haml
= wicked_pdf_stylesheet_link_tag "mail/all"

%table{:width => "100%"}
  %tbody
    %tr{ valign: "top" }
      %td{ :align => "left", colspan: 3 }
        %h6
          = "#{t('.issued_on')}: "
          = l Time.zone.now.to_date
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %h4
          = "#{t('.tax_invoice')}: "
          = "#{@order.number}"
      %td{width: "10%" }
        &nbsp;
      %td{ :align => "right" }
        %h4= @order.order_cycle.andand.name
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %strong= "#{t('.from')}: #{@order.distributor.name}"
        - if @order.distributor.abn.present?
          %br
          = "#{t(:abn)} #{@order.distributor.abn}"
        %br
        = @order.distributor.address.full_address
        %br
        = @order.distributor.email
      %td{width: "10%" }
        &nbsp;
      %td{ :align => "right" }
        %strong= "#{t('.to')}: #{@order.ship_address.full_name}"
        - if @order.customer.code.present?
          %br
          = "#{t('.code')}: #{@order.customer.code}"
        %br
        = @order.ship_address.full_address
        %br
        = "#{@order.customer.email},"
        = "#{@order.bill_address.phone}"

= render 'spree/admin/orders/invoice_table'

- if @order.special_instructions.present?
  %p.callout
    %strong
      = t :customer_instructions
  %p
    %em= @order.special_instructions
  %p
    &nbsp;

- if @order.distributor.invoice_text.present?
  %p
    = @order.distributor.invoice_text

= render 'spree/order_mailer/payment'

app/views/spree/admin/orders/invoice2.html.haml
= wicked_pdf_stylesheet_link_tag "mail/all"


%table{:width => "100%"}
  %tbody
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %h4
          = t :tax_invoice
      - if @order.distributor.display_invoice_logo? && @order.distributor.logo.present?
        %td{ :align => "right", rowspan: 2 }
          = wicked_pdf_image_tag @order.distributor.logo(:small), width: 150, height: 150
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %strong= @order.distributor.name
        %br
        = @order.distributor.address.address_part1
        %br
        = @order.distributor.address.address_part2
        %br
        = @order.distributor.email_address
        - if @order.distributor.phone.present?
          %br
          = @order.distributor.phone
        - if @order.distributor.abn.present?
          %br
          = "#{t :abn} #{@order.distributor.abn}"
        - if @order.distributor.acn.present?
          %br
          = "#{t :acn} #{@order.distributor.acn}"
    %tr{ valign: "top" }
      %td{ :align => "left", colspan: 2 } &nbsp;
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %br
        = t :invoice_issued_on
        = l Time.zone.now.to_date
        %br
        = t :date_of_transaction
        = l @order.completed_at.to_date
        %br
        = t :order_number
        = @order.number
      %td{ :align => "right" }
        = t :invoice_billing_address
        %br
        %strong= @order.ship_address.full_name
        - if @order.customer.code.present?
          %br
          = "Code: #{@order.customer.code}"
        %br
        = @order.ship_address.address_part1
        %br
        = @order.ship_address.address_part2

= render 'spree/admin/orders/invoice_table2'

- if @order.special_instructions.present?
  %p.callout
    %strong
      = t :customer_instructions
  %p
    %em= @order.special_instructions
  %p
    &nbsp;

- if @order.distributor.invoice_text.present?
  %p
    = @order.distributor.invoice_text

= render 'spree/order_mailer/payment'

app/views/spree/admin/orders/new.html.haml
- content_for :page_title do
  = t(:new)

- content_for :page_actions do
  %li= button_link_to t(:back_to_orders_list), spree.admin_orders_path, :icon => 'icon-arrow-left'

= admin_inject_shops 'admin.orders'
= admin_inject_order_cycles

= render 'spree/admin/shared/order_tabs', :current => 'Order Details'

= csrf_meta_tags

%div{"data-hook" => "admin_order_new_header"}
  = render 'spree/shared/error_messages', :target => @order

%div{"ng-app" => "admin.orders", "ng-controller" => "ordersCtrl"}
  %div{"ng-show" => "distributionChosen()"}
    = render 'add_product'

  - unless @order.line_items.any?
    %div{"data-hook" => "admin_order_new_form"}
      #order-form-wrapper
        = render 'form'

- content_for :head do
  = javascript_tag 'var expand_variants = true;'

app/views/spree/admin/orders/set_distribution.html.haml
- content_for :page_title do
  = t(:new)

- content_for :page_actions do
  %li= button_link_to t(:back_to_orders_list), spree.admin_orders_path, :icon => 'icon-arrow-left'

= admin_inject_shops 'admin.orders'
= admin_inject_order_cycles

= render 'spree/admin/shared/order_tabs', :current => 'Order Details'

= csrf_meta_tags

%div{"data-hook" => "admin_order_new_header"}
  = render 'spree/shared/error_messages', :target => @order

%div{"ng-app" => "admin.orders", "ng-controller" => "ordersCtrl"}
  = form_for @order, url: admin_order_url(@order), method: :put do |f|
    = render 'spree/admin/orders/_form/distribution_fields'
    -# This param passed to stop validation error in next page due to no line items in order yet:
    = hidden_field_tag 'suppress_error_msg', "true"
    = button_tag :class => 'secondary radius expand small', :id => 'update-button' do
      %i.icon-arrow-right
      = t(:next)

app/views/spree/admin/orders/ticket.html.haml
!!! Basic
%html
  %head
    <meta content="text/html;charset=ansi" http-equiv="Content-Type">
    = javascript_include_tag "shared/jquery-1.8.0.js"
    = javascript_include_tag "qz/qz-tray.js"
    = javascript_include_tag "qz/sha-256.min.js"
    = javascript_include_tag "qz/rsvp-3.1.0.min.js"
    = javascript_include_tag "qz/jsrsasign-latest-all-min.js"
    :javascript
      var printData = [
      '\x1B' + '\x40',          // init
      '\x1B' + '\x74' + '\x10',
      '\x1B' + '\x61' + '\x31', // center align
      '\x1B' + '\x21' + '\x30', // em mode on
      '#{j(@order.distributor.name)}' + '\x0A',
      '\x1B' + '\x21' + '\x0A' + '\x1B' + '\x45' + '\x0A', // em mode off
      '\x0A',
      '#{j(@order.distributor.address.address_part1)}' + '\x0A',     // text and line break
      '#{j(@order.distributor.address.address_part2)}' + '\x0A',
      '#{j(@order.distributor.email)}' + '\x0A',
      '\x0A',                   // line break    
      '\x1B' + '\x61' + '\x32', // right align
      '#{j(l(Time.zone.now.to_date))}' + '\x0A',
      '#{j(@order.number)}' + '\x0A',
      '\x1B' + '\x61' + '\x30', // left align
      '\x0A',
      '\x1B' + '\x4D' + '\x31', // small text
      "#{'%6s   %-26s%10s%10s' %
      [j(t(:ticket_column_qty)),
      j(t(:ticket_column_item)),
      j(t(:ticket_column_unit_price)),
      j(t(:ticket_column_total_price))]}",
      '\x0A',
      '\x1B' + '\x4D' + '\x30', // normal text
      '__________________________________________' + '\x0A',
      "#{@order.line_items
      .sort_by{ |line_item| line_item.product.name }
      .map { |line_item| '%5d %-19.19s%8.8s%8.8s' %
      [line_item.quantity,
      j(line_item.product.name),
      j(line_item.single_display_amount_with_adjustments.format(symbol: false, with_currency: false)),
      j(line_item.display_amount_with_adjustments.format(symbol: false, with_currency: false))] }
      .join('" + \'\x0A\' + "')}",
      '\x0A',
      "#{checkout_adjustments_for(@order, exclude: [:line_item])
      .reject{ |a| a.amount == 0 }
      .reverse.map { |adjustment| '%5s %-27.27s%8.8s' %
      ["",
      j(raw(adjustment.label)),
      j(display_adjustment_amount(adjustment).format(symbol: false, with_currency: false))] +
      '" + \'\x0A\' + "'}.join }",
      '__________________________________________' + '\x0A',
      '\x0A',
      '\x1B' + '\x45' + '\x0D', // bold on
      "#{'%31s%10s' %
      [j(t(:total_incl_tax)),
      j(@order.display_total.format(with_currency: false))]}",
      '\x1B' + '\x45' + '\x0A', // bold off
      '\x0A',
      "#{display_checkout_taxes_hash(@order).map { |tax_rate, tax_value|
      '%31s%10s' %
      [j(t(:tax_total, rate: tax_rate)),
      j(tax_value.format(with_currency: false))] +
      '" + \'\x0A\' + "'}.join }",
      "#{'%31s%10s' %
      [j(t(:total_excl_tax)),
      j(display_checkout_total_less_tax(@order).format(with_currency: false))]}",
      '\x0A',
      '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A' + '\x0A',
      '\x1B' + '\x69',          // cut paper
      ];
    = javascript_include_tag "qz/ticket-popup.js"
  %body
    %div#printer-list